"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { parseEther } from "viem";
import { useCreateEvent, useTxReceipt } from "@/utils/useContractHook";
import { CONTRACT_ABI, CONTRACT_ADDRESS } from "@/utils/contract";


interface AIEventPayload {
  title: string;
  description: string;
  priceBNB: string;
  eventTimeISO: string;
  maxAttendees?: number;
  colorCode?: string;
}

export function AICreateEvent() {
  const [prompt, setPrompt] = useState("");
  const [loadingAI, setLoadingAI] = useState(false);
  const [event, setEvent] = useState<AIEventPayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [aiLocked, setAiLocked] = useState(false);

  const {
    createEvent,
    isPending: isCreatingOnchain,
    data: txHash,
    error: txError,
  } = useCreateEvent();

  
useTxReceipt(txHash, {
  successMessage: "Event published successfully ",
  errorMessage: "Event creation failed",
});


  async function generateEvent() {
    if (aiLocked) return;

    setLoadingAI(true);
    setAiLocked(true); // 🔒 lock after first click
    setError(null);
    setEvent(null);

    try {
      const res = await fetch("/api/ai/create-event", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "AI generation failed");

      setEvent(data);
    } catch (err: any) {
      setError(err.message);
      setAiLocked(false); // 🔓 unlock if AI fails
    } finally {
      setLoadingAI(false);
    }
  }

  function createEventOnchain() {
    if (!event) return;

    // ⏱ Safe date conversion
    const timestampMs = Date.parse(event.eventTimeISO);
    if (Number.isNaN(timestampMs)) {
      setError("Invalid event date generated by AI");
      return;
    }

    const eventTimeUnix = BigInt(Math.floor(timestampMs / 1000));

    // 👥 Safe maxAttendees conversion
    const maxAttendees =
      typeof event.maxAttendees === "number" &&
      Number.isFinite(event.maxAttendees)
        ? BigInt(Math.floor(event.maxAttendees))
        : BigInt(0);

    // 💰 Safe price conversion
    let priceWei: bigint;
    try {
      priceWei = parseEther(event.priceBNB);
    } catch {
      setError("Invalid price generated by AI");
      return;
    }

    createEvent({
      address: CONTRACT_ADDRESS,
      abi: CONTRACT_ABI,
      functionName: "createEvent",
      args: [
        event.title,
        event.description,
        priceWei,
        eventTimeUnix,
        maxAttendees,
        event.colorCode ?? "#F875AA",
      ],
    });
  }

  return (
    <div
      className="
      h-full
      w-full
      max-w-xl
      mx-auto
      flex
      flex-col
      rounded-2xl
      border
    "
      style={{
        backgroundColor: "rgba(255,255,255,0.7)",
        borderColor: "var(--color-border)",
        color: "var(--color-text)",
      }}
    >
      {/* HEADER */}
      <div
        className="px-6 py-4 border-b"
        style={{ borderColor: "var(--color-border)" }}
      >
        <h2 className="text-lg font-semibold">Akcess Agent</h2>
        <p className="text-xs opacity-70">
          Use Akcess to generate and publish events on-chain.{" "}
        </p>
      </div>

      {/* CHAT / AI OUTPUT */}
      <div
        className="
        flex-1
        overflow-y-auto
        p-6
        space-y-4
      "
      >
        {!event && !loadingAI && (
          <div className="text-sm opacity-60 leading-relaxed">
            <p className="mb-1">Include:</p>

            <ul className="list-disc list-inside space-y-1">
              <li>
                <strong>Event name</strong> and purpose
              </li>
              <li>
                <strong>Date</strong> (e.g. “tomorrow”, “June 15”, or a full
                date)
              </li>
              <li>
                <strong>Price in BNB</strong> (e.g. 0.000001)
              </li>
              <li>
                <strong>Max attendees</strong> (or say “unlimited”)
              </li>
            </ul>

            <div className="mt-3">
              <span className="block">Example:</span>
              <em className="block mt-1">
                “Create a fresher’s party tomorrow, price 0.000001 BNB,
                unlimited seats”
              </em>
            </div>
          </div>
        )}

        {loadingAI && <p className="text-sm opacity-70">Thinking…</p>}

        {error && (
          <p className="text-sm" style={{ color: "var(--color-primary)" }}>
            {error}
          </p>
        )}
        {event && (
          <div
            className="rounded-xl border p-5 space-y-4"
            style={{
              borderColor: event.colorCode || "var(--color-border)",
              backgroundColor: "var(--color-bg)",
            }}
          >
            {/* TITLE */}
            <div>
              <h3 className="text-base font-semibold">{event.title}</h3>
              <p className="mt-1 text-sm opacity-80">{event.description}</p>
            </div>

            {/* DETAILS */}
            <div className="text-sm space-y-2">
              <div className="flex justify-between">
                <span className="opacity-70">Event date & time</span>
                <span className="font-medium">
                  {new Date(event.eventTimeISO).toLocaleString()}
                </span>
              </div>

              <div className="flex justify-between">
                <span className="opacity-70">Ticket price</span>
                <span className="font-medium">
                  {Number(event.priceBNB) === 0
                    ? "Free"
                    : `${event.priceBNB} BNB`}
                </span>
              </div>

              <div className="flex justify-between">
                <span className="opacity-70">Maximum attendees</span>
                <span className="font-medium">
                  {event.maxAttendees ? event.maxAttendees : "Unlimited"}
                </span>
              </div>
            </div>

            {/* ON-CHAIN NOTICE */}
            <div
              className="rounded-lg p-3 text-xs leading-relaxed mt-8"
              style={{
                backgroundColor: "rgba(0,0,0,0.03)",
                border: "1px solid var(--color-border)",
              }}
            >
              <i>
                This action publishes the event on the BNB Smart Chain Test
                Network on-chain and cannot be reversed.
              </i>
            </div>

            {/* CONFIRM BUTTON */}
            <motion.button
              onClick={createEventOnchain}
              disabled={isCreatingOnchain}
              className="w-full rounded-lg px-4 py-2 font-semibold text-white cursor-pointer"
              style={{
                backgroundColor: "var(--color-primary)",
                opacity: isCreatingOnchain ? 0.6 : 1,
                cursor: isCreatingOnchain ? "not-allowed" : "pointer",
              }}
              whileHover={!isCreatingOnchain ? { scale: 1.03 } : {}}
              whileTap={!isCreatingOnchain ? { scale: 0.97 } : {}}
            >
              {isCreatingOnchain ? "Confirming on-chain…" : "Confirm event"}
            </motion.button>

            {/* TX HASH */}
            {txHash && (
              <p
                className="text-xs break-all"
                style={{ color: "var(--color-primary)" }}
              >
                Transaction submitted: {txHash}
              </p>
            )}
          </div>
        )}
      </div>

      {/* PROMPT INPUT (BOTTOM) */}
      <div
        className="p-4 border-t"
        style={{ borderColor: "var(--color-border)" }}
      >
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe your event…"
          rows={3}
          className="w-full rounded-lg p-3 text-sm outline-none resize-none"
          style={{
            backgroundColor: "var(--color-bg)",
            border: "1px solid var(--color-border)",
            color: "var(--color-text)",
          }}
        />

        <motion.button
          onClick={generateEvent}
          disabled={!prompt || loadingAI || aiLocked}
          className="mt-3 w-full rounded-xl px-4 py-3 font-semibold text-white transition-opacity cursor-pointer"
          style={{
            backgroundColor: "var(--color-primary)",
            opacity: aiLocked ? 0.6 : 1, // 👈 visual feedback
            cursor: aiLocked ? "not-allowed" : "pointer",
          }}
          whileHover={
            aiLocked
              ? undefined
              : {
                  scale: 1.02,
                  backgroundColor: "var(--color-primary-hover)",
                }
          }
          whileTap={aiLocked ? undefined : { scale: 0.98 }}
        >
          {loadingAI
            ? "Generating…"
            : aiLocked
              ? "AI Event Generated"
              : "Generate with AI"}
        </motion.button>
      </div>
    </div>
  );
}
