"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { parseEther } from "viem";
import { useCreateEvent } from "@/utils/useContractHook";
import { CONTRACT_ABI, CONTRACT_ADDRESS } from "@/utils/contract";

interface AIEventPayload {
  title: string;
  description: string;
  priceBNB: string;
  eventTimeISO: string;
  maxAttendees?: number;
  colorCode?: string;
}

export function AICreateEvent() {
  const [prompt, setPrompt] = useState("");
  const [loadingAI, setLoadingAI] = useState(false);
  const [event, setEvent] = useState<AIEventPayload | null>(null);
  const [error, setError] = useState<string | null>(null);

  const {
    createEvent,
    isPending: isCreatingOnchain,
    data: txHash,
    error: txError,
  } = useCreateEvent();

  async function generateEvent() {
    setLoadingAI(true);
    setError(null);
    setEvent(null);

    try {
      const res = await fetch("/api/ai/create-event", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "AI generation failed");

      setEvent(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoadingAI(false);
    }
  }

  function createEventOnchain() {
    if (!event) return;

    // ⏱ Safe date conversion
    const timestampMs = Date.parse(event.eventTimeISO);
    if (Number.isNaN(timestampMs)) {
      setError("Invalid event date generated by AI");
      return;
    }

    const eventTimeUnix = BigInt(Math.floor(timestampMs / 1000));

    // 👥 Safe maxAttendees conversion
    const maxAttendees =
      typeof event.maxAttendees === "number" &&
      Number.isFinite(event.maxAttendees)
        ? BigInt(Math.floor(event.maxAttendees))
        : BigInt(0);

    // 💰 Safe price conversion
    let priceWei: bigint;
    try {
      priceWei = parseEther(event.priceBNB);
    } catch {
      setError("Invalid price generated by AI");
      return;
    }

    createEvent({
      address: CONTRACT_ADDRESS,
      abi: CONTRACT_ABI,
      functionName: "createEvent",
      args: [
        event.title,
        event.description,
        priceWei,
        eventTimeUnix,
        maxAttendees,
        event.colorCode ?? "#F875AA",
      ],
    });
  }

  return (
    <div
      className="w-full max-w-xl space-y-4 rounded-2xl p-6 border"
      style={{
        backgroundColor: "rgba(255,255,255,0.7)",
        borderColor: "var(--color-border)",
        color: "var(--color-text)",
      }}
    >
      <h2 className="text-lg font-semibold">Create Event with AI</h2>

      {/* PROMPT INPUT */}
      <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Describe your event…"
        rows={4}
        className="w-full rounded-lg p-3 text-sm outline-none"
        style={{
          backgroundColor: "var(--color-bg)",
          border: "1px solid var(--color-border)",
          color: "var(--color-text)",
        }}
      />

      {/* AI BUTTON */}
      <motion.button
        onClick={generateEvent}
        disabled={!prompt || loadingAI}
        className="w-full rounded-xl px-4 py-3 font-semibold text-white"
        style={{ backgroundColor: "var(--color-primary)" }}
        whileHover={{
          scale: 1.03,
          backgroundColor: "var(--color-primary-hover)",
        }}
        whileTap={{ scale: 0.97 }}
      >
        {loadingAI ? "Generating…" : "Generate with AI"}
      </motion.button>

      {error && (
        <p className="text-sm" style={{ color: "var(--color-primary)" }}>
          {error}
        </p>
      )}

      {/* AI PREVIEW */}
      {event && (
        <div
          className="rounded-xl border p-4 space-y-3"
          style={{
            borderColor: event.colorCode || "var(--color-border)",
            backgroundColor: "var(--color-bg)",
          }}
        >
          <h3 className="font-semibold">{event.title}</h3>
          <p className="text-sm opacity-80">{event.description}</p>

          <div className="text-xs space-y-1 opacity-80">
            <p>💰 {event.priceBNB} BNB</p>
            <p>📅 {new Date(event.eventTimeISO).toLocaleString()}</p>
            {event.maxAttendees && <p>👥 {event.maxAttendees} seats</p>}
          </div>

          {/* ONCHAIN BUTTON */}
          <motion.button
            onClick={createEventOnchain}
            disabled={isCreatingOnchain}
            className="w-full rounded-lg px-4 py-2 font-semibold text-white"
            style={{ backgroundColor: "var(--color-primary)" }}
            whileHover={{
              scale: 1.03,
              backgroundColor: "var(--color-primary-hover)",
            }}
            whileTap={{ scale: 0.97 }}
          >
            {isCreatingOnchain ? "Creating on-chain…" : "Create On-chain Event"}
          </motion.button>

          {txHash && (
            <p
              className="text-xs break-all"
              style={{ color: "var(--color-primary)" }}
            >
              Tx sent: {txHash}
            </p>
          )}

          {txError && (
            <p className="text-xs" style={{ color: "var(--color-primary)" }}>
              {txError.message}
            </p>
          )}
        </div>
      )}
    </div>
  );
}
